services:
  catalogdb:
    image: postgres

  catalog_api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: src/Services/Catalog/Catalog_API/Dockerfile


volumes:
  postgres_catalog:
  postgres_basket:





