@baseUrl = https://localhost:6060
@productId = 5334c996-8457-4cf0-815c-ed2b77c4ff61
@category = Smart Phone

### Get Health Check
GET {{baseUrl}}/health
Accept: application/json

### GET Request 
GET {{baseUrl}}/products
Accept: application/json

### GET Request Paganation query
GET {{baseUrl}}/products?pageNumber=1&pageSize=5
Accept: application/json

### GET Request By Id 
GET {{baseUrl}}/products/{{productId}}
Accept: application/json

### GET Request By Category 
GET {{baseUrl}}/products/category/{{category}}
Accept: application/json


### POST Request
POST {{baseUrl}}/products
Content-Type: application/json

{
    "Name": "New Product G",
    "Category": ["c1", "c2"],
    "Description": "Description Product A",
    "ImageFile": "ImageFile Product A",
    "Price": 199
}

### PUT Request
PUT {{baseUrl}}/products
Content-Type: application/json

{
    "Id": "{{productId}}",
    "Name": "New Product A",
    "Category": ["c2", "c3"],
    "Description": "Description Product A",
    "ImageFile": "ImageFile Product A",
    "Price": 199
}

### DELETE Request By Id 
DELETE {{baseUrl}}/products/{{productId}}
Accept: application/json



