@baseUrl = https://localhost:5050

### GET Request 
GET {{baseUrl}}
Accept: application/json

###

### POST Request
POST {{baseUrl}}/products
Content-Type: application/json

{
    "Name": "New Product A",
    "Category": ["c1", "c2"],
    "Description": "Description Product A",
    "ImageFile": "ImageFile Product A",
    "Price": 199
}



