@baseUrl = https://localhost:5053

### Get Health Request
GET {{baseUrl}}/health
Accept: application/json


### Get Orders Request
GET {{baseUrl}}/orders?PageIndex=0&PageSize=2
Accept: application/json


### Get Orders By Name Request
GET {{baseUrl}}/orders/ORD_2
Accept: application/json


### Get Orders By Customer Request
GET {{baseUrl}}/orders/customer/58c49479-ec65-4de2-86e7-033c546291aa
Accept: application/json


### POST Request
POST {{baseUrl}}/orders
Content-Type: application/json

{
	"Order": 
        {
        	"CustomerId": "58c49479-ec65-4de2-86e7-033c546291aa",
            "OrderName": "ORD_4",
            "ShippingAddress": 
            	{
            		"FirstName": "Valentina",
	                "LastName": "Legros",
	                "EmailAddress": "valeg@xmail.com",
	                "AddressLine": "Wiegand Pass Suite 825",
	                "Country": "USA",
	                "State": "Oklahoma",
	                "ZipCode": "41248"
            	},
            "BillingAddress": 
            	{
            		"FirstName": "Valentina",
	                "LastName": "Legros",
	                "EmailAddress": "valeg@xmail.com",
	                "AddressLine": "Wiegand Pass Suite 825",
	                "Country": "USA",
	                "State": "Oklahoma",
	                "ZipCode": "41248"
            	},
            "Payment": 
            	{
            		"CardName": "CARD_1",
	                "CardNumber": "875-444-3739",
	                "Expiration": "12/29",
	                "Cvv": "455",
	                "PaymentMethod": 1
            	},
            "Status": 2,
            "OrderItems": [
                {
	                "ProductId": "5334c996-8457-4cf0-815c-ed2b77c4ff61",
	                //"ProductName": "IPhone X",
	                "Quantity": 2,
	                "Price": 500
                },
                {
	                "ProductId": "c67d6323-e8b1-4bdf-9a75-b0d0d2e7e914",
	                //"ProductName": "Samsung 10",
	                "Quantity": 1,
	                "Price": 500
                }
            ]  
        }
}


### PUT Request
PUT {{baseUrl}}/orders
Content-Type: application/json

{
	"Order": 
        {
            "Id": "354c00f6-b04c-46ed-8d6d-f9f42d7bdf98",
        	"CustomerId": "58c49479-ec65-4de2-86e7-033c546291aa",
            "OrderName": "ORD_5",
            "ShippingAddress": 
            	{
            		"FirstName": "Mehmet",
	                "LastName": "Legros",
	                "EmailAddress": "valeg@xmail.com",
	                "AddressLine": "Wiegand Pass Suite 825",
	                "Country": "USA",
	                "State": "New York",
	                "ZipCode": "41248"
            	},
            "BillingAddress": 
            	{
            		"FirstName": "Mehmet",
	                "LastName": "Legros",
	                "EmailAddress": "valeg@xmail.com",
	                "AddressLine": "Wiegand Pass Suite 825",
	                "Country": "USA",
	                "State": "Oklahoma",
	                "ZipCode": "41248"
            	},
            "Payment": 
            	{
            		"CardName": "CARD_2",
	                "CardNumber": "875-444-3739",
	                "Expiration": "12/29",
	                "CVV": "455",
	                "PaymentMethod": 1
            	},
            "Status": 2,
            "OrderItems": [
                {
	                "ProductId": "5334c996-8457-4cf0-815c-ed2b77c4ff61",
	                //"ProductName": "IPhone X",
	                "Quantity": 2,
	                "Price": 500
                },
                {
	                "ProductId": "c67d6323-e8b1-4bdf-9a75-b0d0d2e7e914",
	                //"ProductName": "Samsung 10",
	                "Quantity": 1,
	                "Price": 500
                }
            ]  
        }
}

### DELETE Request By Id
DELETE {{baseUrl}}/orders/354c00f6-b04c-46ed-8d6d-f9f42d7bdf98
Accept: application/json