namespace Ordering.Domain.Abstractions;

//These represent aggregate roots—central pieces in the domain that encapsulate related entities and enforce business rules.


/*
  Marks an entity as an Aggregate Root with:

    - DomainEvents: events generated by the aggregate

    - ClearDomainEvents(): clears the event queue (typically after persisting or dispatching)
*/
public interface IAggregate : IEntity
{
    IReadOnlyList<IDomainEvent> DomainEvents { get; }
    IDomainEvent[] ClearDomainEvents();
}


// Combines aggregate and entity behaviors, including a generic Id.
public interface IAggregate<T> : IAggregate, IEntity<T>
{
}
